Repository italia/docs.italia.it, pull requests merged in 2019-11, with the labels that each got.

#396 Fix eslint on production branch
  .travis.yml
Labels: bug, frontend

#393 Avoid double markdown registration errors
  readthedocs/rtd_tests/tests/test_docsitalia.py
  readthedocs/templates/docsitalia/overrides/doc_builder/conf.py.tmpl
Labels: bug

#405 Stile "card": divisori e icone
  media/docsitalia/css/core.css
  readthedocs/templates/docsitalia/includes/card.html
Labels: backport

#407 Removes paragraph with Trello link
  readthedocs/templates/docsitalia/about.html
Labels: backport

#406 Adds proper links to pages
  readthedocs/templates/docsitalia/about.html
  readthedocs/templates/docsitalia/docsitalia_homepage.html
Labels: backport

#409 Fix evidence bar
  readthedocs/templates/docsitalia/includes/header.html
Labels: backport

#410 Fix cookie bar spacing and buttons
  readthedocs/templates/docsitalia/includes/cookiebar.html
Labels: backport

#402 #399 Style tags
  media/docsitalia/css/core.css
Labels: backport

#413 Add command to competely rebuild indices and reindexing ES
  docker/es_rebuild_indices.sh
Labels: backport, nuova feature

#414 #392 Change Project bar and Admin settings
  readthedocs/templates/docsitalia/overrides/core/project_bar_base.html
  readthedocs/templates/docsitalia/overrides/projects/project_edit_base.html
Labels: backport

#412 Proper analyzer configuration
  readthedocs/docsitalia/settings/docker.py
  readthedocs/search/documents.py
Labels: backport, bug

#415 Add missing projects migration
  readthedocs/docsitalia/migrations/0017_patch-project-version.py
  readthedocs/docsitalia/migrations_schema_utils.py
Labels: backport

#420 Use version in DocumentRedirect view
  readthedocs/docsitalia/views/core_views.py
Labels: backport

#398 Add command to create allowed_tags
  readthedocs/docsitalia/management/commands/import_allowed_tags.py
  readthedocs/docsitalia/migrations/0018_create_allowed_tags.py
Labels: backport, bug

#419 Disconnect django_elasticsearch_dsl signals when syncing publishers
  readthedocs/docsitalia/oauth/services/github.py
  readthedocs/rtd_tests/tests/test_docsitalia.py
Labels: backport

#422 Registration email text
  readthedocs/locale/it/LC_MESSAGES/django.po
Labels: backport

#425 Fix search url for publisher logo
  readthedocs/templates/docsitalia/publisher_detail.html
Labels: backport

#421 Fix card disposition
  media/docsitalia/css/core.css
  readthedocs/templates/docsitalia/overrides/search/elastic_search.html
Labels: backport

#372 #222 Initial import webhook
  readthedocs/docsitalia/views/core_views.py
  readthedocs/rtd_tests/tests/test_docsitalia_views.py
  readthedocs/templates/docsitalia/overrides/core/project_bar_base.html
Labels: backport, bug

#417 Allineamento testo iscrizione
  media/docsitalia/css/core.css
  readthedocs/templates/docsitalia/overrides/account/login.html
  readthedocs/templates/docsitalia/overrides/account/signup.html
Labels: backport
